apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx_rs
  labels: 
    app: nginx
spec: 
  minReadySeconds: 1
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
  template: 
    metadata: 
      name: nginx_rs
    spec: 
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80  
        - name: alpine
          image: alpine:latest
          

