apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  template: 
    metadata:
      name: jobtemp
    spec:
      restartPolicy: "Never"
      containers:
        - image: httpd:latest
          name: httpdjob
          command: 
            - sleep
            - 1d
