apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec: 
  template: 
    metadata:
      name: jobtemp
    spec:
      containers:
        - image: alpine:latest
          name: alpinejob
          command: 
            - sleep
            - 1d
